# Наша музика. За бажанням можете запропонувати сюди ще щось!
- type: entity
  id: CheeburbrCrateMusicCds
  parent: CrateGenericSteel
  name: cd disks crate Moff Co # Англійською, щоб не ламало список
  description: Цілий ящик відбірних пісень. Містить 15 випадкових позицій з збірнику "Потўжниџ-Крижопі́ль". Тепер на Компакт-дисках! Випуск та виробництво спонсоровано корпорацію Мофф ко.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: CheeburbrRandomMusicCD
        rolls: 15

- type: entityTable
  id: CheeburbrRandomMusicCD
  table: !type:GroupSelector
    children:
    - id: CheeburbrCdDiskAlexandraStanMrSaxobeat
    - id: CheeburbrCdDiskAzumiTakahashiLotusJuiceItsGoingDownNow
    - id: CheeburbrCdDiskBonnieTylerHoldingOutForAHero
    - id: CheeburbrCdDiskBettaLemmeBambola
    - id: CheeburbrCdDiskBillyIdolEyesWithoutAFace
    - id: CheeburbrCdDiskBlackSabbathLadyEvil
    - id: CheeburbrCdDiskBritneySpearsBabyOneMoreTime
    - id: CheeburbrCdDiskCalogeroPassiFaceALaMer
    - id: CheeburbrCdDiskColdplayAdventureOfALifetime
    - id: CheeburbrCdDiskDavidGuettaBebeRexhaJBalvinSayMyName
    - id: CheeburbrCdDiskDepecheModePersonalJesus
    - id: CheeburbrCdDiskDrPhonicsCodeRed
    - id: CheeburbrCdDiskDuranDuranInvisible
    - id: CheeburbrCdDiskEltonJohnImStillStanding
    - id: CheeburbrCdDiskEurythmicsSweetDreamsAreMadeOfThis
    - id: CheeburbrCdDiskEveryMoveAPictureSignsOfLife
    - id: CheeburbrCdDiskFasionDansez
    - id: CheeburbrCdDiskFloRidaWhistle
    - id: CheeburbrCdDiskGaryNumanMe
    - id: CheeburbrCdDiskGaryNumanTubewayArmyAreFriendsElectric
    - id: CheeburbrCdDiskGrandCorpsMaladeBertholletCheminsDeTraverse
    - id: CheeburbrCdDiskGwenStefaniAkonTheSweetEscape
    - id: CheeburbrCdDiskHieroglyphicsLetItRoll
    - id: CheeburbrCdDiskHowlinJacksonJellyRollBlues
    - id: CheeburbrCdDiskInfectedMushroomNeverMind
    - id: CheeburbrCdDiskJanValtaAdamSporkaRattayFeasts
    - id: CheeburbrCdDiskJourneyWhosCryingNow
    - id: CheeburbrCdDiskJustinBieberLudacrisBaby
    - id: CheeburbrCdDiskKatyPerryIKissedAGirl
    - id: CheeburbrCdDiskLadyGagaTheDeadDance
    - id: CheeburbrCdDiskMadHeads
    - id: CheeburbrCdDiskManeskinBeggin
    - id: CheeburbrCdDiskMasayoshiTakanakaBrasilianSkies
    - id: CheeburbrCdDiskMichaelJacksonRockWithYou
    - id: CheeburbrCdDiskMidgeUreTheManWhoSoldTheWorld
    - id: CheeburbrCdDiskMichaelSembelloManiacFromFlashdance
    - id: CheeburbrCdDiskMinakoYoshidaMidnightDriver
    - id: CheeburbrCdDiskMittsiesVitality
    - id: CheeburbrCdDiskQuestionableSlightlyStoopid
    - id: CheeburbrCdDiskTameImpalaTheLessIKnowTheBetter
    - id: CheeburbrCdDiskWolfmotherLoveTrain
    - id: CheeburbrCdDiskPaulKalkbrennerStromaeQueCeSoitClair
    - id: CheeburbrCdDiskRoseBrunoMarsApt
    - id: CheeburbrCdDiskSelenaGomezTheSceneLoveYouLikeALoveSong
    - id: CheeburbrCdDiskSherylCrowRealGone
    - id: CheeburbrCdDiskShihokoHirataHeartbeatHeartbreak
    - id: CheeburbrCdDiskSkverVilni
    - id: CheeburbrCdDiskSpandauBalletGold
    - id: CheeburbrCdDiskStromaeSante
    - id: CheeburbrCdDiskSuunsUpPastTheNursery
    - id: CheeburbrCdDiskSynapsonOumouSangareBensema
    - id: CheeburbrCdDiskSynapsonTimDupLassToujours
    - id: CheeburbrCdDiskTheChordsShBoom
    - id: CheeburbrCdDiskTheRahBandMessagesFromTheStars
    - id: CheeburbrCdDiskTheTemptationsAintNoSunSinceYouveBeenGone
    - id: CheeburbrCdDiskTheTemptationsBallOfConfusion
    - id: CheeburbrCdDiskThmkMolod
    - id: CheeburbrCdDiskTikZapahWar
    - id: CheeburbrCdDiskTwistedSisterKingOfTheFools
    - id: CheeburbrCdDiskVariousArtistsBosanskaArtiljerija
    - id: CheeburbrCdDiskWhiteZombieImYourBoogieman
    - id: CheeburbrCdDiskWoodkidIron
