# SPDX-License-Identifier: AGPL-3.0-or-later
# This is shit and needs cleanup but since we are technically running this after a workflow that runs on the fork and not master i kinda want to make sure we use nothing from that workflow
# Forgive me for the mess. This is overkill.
# I am future planning against shit that will never end up mattering.
name: "Labels: Approved"

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    if: ${{ (github.repository == 'Pgriha/Monolith') && (github.event.review.state == 'APPROVED') }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: tspascoal/get-user-teams-membership@v3
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: "maintainers"
        GITHUB_TOKEN: ${{ secrets.LABELER_PAT }}
    - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        number: ${{ steps.pr-context.outputs.number }}
        labels: "S: Прийнятий"

    - name: Remove Other Labels on Approved
      if: steps.check-approvals.outputs.approvals >= 2
      uses: actions-ecosystem/action-remove-labels@v1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        number: ${{ steps.pr-context.outputs.number }}
        labels: |
          S: Needs Review
          S: Needs Second Approval

    - name: Add Second Approval Requirement
      if: steps.check-approvals.outputs.approvals == 1
      uses: actions-ecosystem/action-add-labels@v1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        number: ${{ steps.pr-context.outputs.number }}
        labels: |
          S: Needs Review
          S: Needs Second Approval

    - name: Remove Other Labels on Second Approval
      if: steps.check-approvals.outputs.approvals == 1
      uses: actions-ecosystem/action-remove-labels@v1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        number: ${{ steps.pr-context.outputs.number }}
        labels: "S: Approved"

    - name: Remove All Other Labels if No Approval
      if: steps.check-approvals.outputs.approvals < 1
      uses: actions-ecosystem/action-remove-labels@v1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        number: ${{ steps.pr-context.outputs.number }}
        labels: |
          S: Needs Review
          S: Needs Second Approval

